// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: rpc/alert.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AlertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlertId       string                 `protobuf:"bytes,1,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertRequest) Reset() {
	*x = AlertRequest{}
	mi := &file_rpc_alert_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertRequest) ProtoMessage() {}

func (x *AlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_alert_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertRequest.ProtoReflect.Descriptor instead.
func (*AlertRequest) Descriptor() ([]byte, []int) {
	return file_rpc_alert_proto_rawDescGZIP(), []int{0}
}

func (x *AlertRequest) GetAlertId() string {
	if x != nil {
		return x.AlertId
	}
	return ""
}

type AlertData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlertName     string                 `protobuf:"bytes,1,opt,name=alert_name,json=alertName,proto3" json:"alert_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertData) Reset() {
	*x = AlertData{}
	mi := &file_rpc_alert_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertData) ProtoMessage() {}

func (x *AlertData) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_alert_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertData.ProtoReflect.Descriptor instead.
func (*AlertData) Descriptor() ([]byte, []int) {
	return file_rpc_alert_proto_rawDescGZIP(), []int{1}
}

func (x *AlertData) GetAlertName() string {
	if x != nil {
		return x.AlertName
	}
	return ""
}

var File_rpc_alert_proto protoreflect.FileDescriptor

const file_rpc_alert_proto_rawDesc = "" +
	"\n" +
	"\x0frpc/alert.proto\x12\x03rpc\")\n" +
	"\fAlertRequest\x12\x19\n" +
	"\balert_id\x18\x01 \x01(\tR\aalertId\"*\n" +
	"\tAlertData\x12\x1d\n" +
	"\n" +
	"alert_name\x18\x01 \x01(\tR\talertName2A\n" +
	"\fAlertService\x121\n" +
	"\fGetAlertData\x12\x11.rpc.AlertRequest\x1a\x0e.rpc.AlertDataB\x1eZ\x1calerting-platform/common/rpcb\x06proto3"

var (
	file_rpc_alert_proto_rawDescOnce sync.Once
	file_rpc_alert_proto_rawDescData []byte
)

func file_rpc_alert_proto_rawDescGZIP() []byte {
	file_rpc_alert_proto_rawDescOnce.Do(func() {
		file_rpc_alert_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_alert_proto_rawDesc), len(file_rpc_alert_proto_rawDesc)))
	})
	return file_rpc_alert_proto_rawDescData
}

var file_rpc_alert_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_alert_proto_goTypes = []any{
	(*AlertRequest)(nil), // 0: rpc.AlertRequest
	(*AlertData)(nil),    // 1: rpc.AlertData
}
var file_rpc_alert_proto_depIdxs = []int32{
	0, // 0: rpc.AlertService.GetAlertData:input_type -> rpc.AlertRequest
	1, // 1: rpc.AlertService.GetAlertData:output_type -> rpc.AlertData
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_alert_proto_init() }
func file_rpc_alert_proto_init() {
	if File_rpc_alert_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_alert_proto_rawDesc), len(file_rpc_alert_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_alert_proto_goTypes,
		DependencyIndexes: file_rpc_alert_proto_depIdxs,
		MessageInfos:      file_rpc_alert_proto_msgTypes,
	}.Build()
	File_rpc_alert_proto = out.File
	file_rpc_alert_proto_goTypes = nil
	file_rpc_alert_proto_depIdxs = nil
}
