// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: rpc/services.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServicesInfoForIncident struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Services      []*ServiceInfoForIncident `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServicesInfoForIncident) Reset() {
	*x = ServicesInfoForIncident{}
	mi := &file_rpc_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServicesInfoForIncident) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicesInfoForIncident) ProtoMessage() {}

func (x *ServicesInfoForIncident) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServicesInfoForIncident.ProtoReflect.Descriptor instead.
func (*ServicesInfoForIncident) Descriptor() ([]byte, []int) {
	return file_rpc_services_proto_rawDescGZIP(), []int{0}
}

func (x *ServicesInfoForIncident) GetServices() []*ServiceInfoForIncident {
	if x != nil {
		return x.Services
	}
	return nil
}

type ServiceInfoForIncident struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ServiceId           uint64                 `protobuf:"varint,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	AlertWindow         int64                  `protobuf:"varint,2,opt,name=alert_window,json=alertWindow,proto3" json:"alert_window,omitempty"`
	AllowedResponseTime int64                  `protobuf:"varint,3,opt,name=allowed_response_time,json=allowedResponseTime,proto3" json:"allowed_response_time,omitempty"`
	Oncallers           []string               `protobuf:"bytes,4,rep,name=oncallers,proto3" json:"oncallers,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ServiceInfoForIncident) Reset() {
	*x = ServiceInfoForIncident{}
	mi := &file_rpc_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfoForIncident) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfoForIncident) ProtoMessage() {}

func (x *ServiceInfoForIncident) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfoForIncident.ProtoReflect.Descriptor instead.
func (*ServiceInfoForIncident) Descriptor() ([]byte, []int) {
	return file_rpc_services_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceInfoForIncident) GetServiceId() uint64 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

func (x *ServiceInfoForIncident) GetAlertWindow() int64 {
	if x != nil {
		return x.AlertWindow
	}
	return 0
}

func (x *ServiceInfoForIncident) GetAllowedResponseTime() int64 {
	if x != nil {
		return x.AllowedResponseTime
	}
	return 0
}

func (x *ServiceInfoForIncident) GetOncallers() []string {
	if x != nil {
		return x.Oncallers
	}
	return nil
}

var File_rpc_services_proto protoreflect.FileDescriptor

const file_rpc_services_proto_rawDesc = "" +
	"\n" +
	"\x12rpc/services.proto\x12\x03rpc\x1a\x1bgoogle/protobuf/empty.proto\"R\n" +
	"\x17ServicesInfoForIncident\x127\n" +
	"\bservices\x18\x01 \x03(\v2\x1b.rpc.ServiceInfoForIncidentR\bservices\"\xac\x01\n" +
	"\x16ServiceInfoForIncident\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\x04R\tserviceId\x12!\n" +
	"\falert_window\x18\x02 \x01(\x03R\valertWindow\x122\n" +
	"\x15allowed_response_time\x18\x03 \x01(\x03R\x13allowedResponseTime\x12\x1c\n" +
	"\toncallers\x18\x04 \x03(\tR\toncallers2d\n" +
	"\x16IncidentManagerService\x12J\n" +
	"\x12GetAllServicesInfo\x12\x16.google.protobuf.Empty\x1a\x1c.rpc.ServicesInfoForIncidentB\x1eZ\x1calerting-platform/common/rpcb\x06proto3"

var (
	file_rpc_services_proto_rawDescOnce sync.Once
	file_rpc_services_proto_rawDescData []byte
)

func file_rpc_services_proto_rawDescGZIP() []byte {
	file_rpc_services_proto_rawDescOnce.Do(func() {
		file_rpc_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_services_proto_rawDesc), len(file_rpc_services_proto_rawDesc)))
	})
	return file_rpc_services_proto_rawDescData
}

var file_rpc_services_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_services_proto_goTypes = []any{
	(*ServicesInfoForIncident)(nil), // 0: rpc.ServicesInfoForIncident
	(*ServiceInfoForIncident)(nil),  // 1: rpc.ServiceInfoForIncident
	(*emptypb.Empty)(nil),           // 2: google.protobuf.Empty
}
var file_rpc_services_proto_depIdxs = []int32{
	1, // 0: rpc.ServicesInfoForIncident.services:type_name -> rpc.ServiceInfoForIncident
	2, // 1: rpc.IncidentManagerService.GetAllServicesInfo:input_type -> google.protobuf.Empty
	0, // 2: rpc.IncidentManagerService.GetAllServicesInfo:output_type -> rpc.ServicesInfoForIncident
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_services_proto_init() }
func file_rpc_services_proto_init() {
	if File_rpc_services_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_services_proto_rawDesc), len(file_rpc_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_services_proto_goTypes,
		DependencyIndexes: file_rpc_services_proto_depIdxs,
		MessageInfos:      file_rpc_services_proto_msgTypes,
	}.Build()
	File_rpc_services_proto = out.File
	file_rpc_services_proto_goTypes = nil
	file_rpc_services_proto_depIdxs = nil
}
