// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.32.1
// source: rpc/services.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IncidentManagerService_GetAllServicesInfo_FullMethodName = "/rpc.IncidentManagerService/GetAllServicesInfo"
)

// IncidentManagerServiceClient is the client API for IncidentManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IncidentManagerServiceClient interface {
	GetAllServicesInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ServicesInfoForIncident, error)
}

type incidentManagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIncidentManagerServiceClient(cc grpc.ClientConnInterface) IncidentManagerServiceClient {
	return &incidentManagerServiceClient{cc}
}

func (c *incidentManagerServiceClient) GetAllServicesInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ServicesInfoForIncident, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServicesInfoForIncident)
	err := c.cc.Invoke(ctx, IncidentManagerService_GetAllServicesInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IncidentManagerServiceServer is the server API for IncidentManagerService service.
// All implementations must embed UnimplementedIncidentManagerServiceServer
// for forward compatibility.
type IncidentManagerServiceServer interface {
	GetAllServicesInfo(context.Context, *emptypb.Empty) (*ServicesInfoForIncident, error)
	mustEmbedUnimplementedIncidentManagerServiceServer()
}

// UnimplementedIncidentManagerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIncidentManagerServiceServer struct{}

func (UnimplementedIncidentManagerServiceServer) GetAllServicesInfo(context.Context, *emptypb.Empty) (*ServicesInfoForIncident, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllServicesInfo not implemented")
}
func (UnimplementedIncidentManagerServiceServer) mustEmbedUnimplementedIncidentManagerServiceServer() {
}
func (UnimplementedIncidentManagerServiceServer) testEmbeddedByValue() {}

// UnsafeIncidentManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IncidentManagerServiceServer will
// result in compilation errors.
type UnsafeIncidentManagerServiceServer interface {
	mustEmbedUnimplementedIncidentManagerServiceServer()
}

func RegisterIncidentManagerServiceServer(s grpc.ServiceRegistrar, srv IncidentManagerServiceServer) {
	// If the following call panics, it indicates UnimplementedIncidentManagerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IncidentManagerService_ServiceDesc, srv)
}

func _IncidentManagerService_GetAllServicesInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IncidentManagerServiceServer).GetAllServicesInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IncidentManagerService_GetAllServicesInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IncidentManagerServiceServer).GetAllServicesInfo(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// IncidentManagerService_ServiceDesc is the grpc.ServiceDesc for IncidentManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IncidentManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.IncidentManagerService",
	HandlerType: (*IncidentManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllServicesInfo",
			Handler:    _IncidentManagerService_GetAllServicesInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/services.proto",
}
